// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzjvmhoyxejewhplyzpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6anZtaG95eGVqZXdocGx5enB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDM0MDgsImV4cCI6MjA3MDgxOTQwOH0.vGCbRzgAL7IRAdUzkxN8iH8PXVl2l88f9paXqt8NHtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
